accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "AGPL-3.0-or-later",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "bzip2-1.0.6",
    "CDLA-Permissive-2.0",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "OpenSSL",
    "BSL-1.0",
    "CC0-1.0",
    "GPL-3.0",
    "GPL-3.0-or-later",
    "LGPL-3.0",
    "LGPL-3.0-or-later",
    "AGPL-3.0",
    "MPL-2.0",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false

